// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models
{
    public partial class KoiProfile
    {
        public KoiProfile()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int Koi_Id { get; set; }
        public int? Type_Id { get; set; }
        public int? Farm_Id { get; set; }
        public string Koi_Name { get; set; }
        public int? Quantity { get; set; }
        public double? Size { get; set; }
        public double? Price { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public DateTime? Create_At { get; set; }
        public DateTime? Update_At { get; set; }
        public double? Rating_Average_Value { get; set; }
        public string Status { get; set; }

        public virtual KoiFarm Farm { get; set; }
        public virtual KoiType Type { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}