// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models
{
    public partial class User
    {
        public User()
        {
            Feedbacks = new HashSet<Feedback>();
            OrderDetails = new HashSet<OrderDetail>();
            Orders = new HashSet<Order>();
            Ratings = new HashSet<Rating>();
            UserProfiles = new HashSet<UserProfile>();
        }

        public int User_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? Role_Id { get; set; }
        public string Status { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}